// LOCALHOST

###localhost
GET http://localhost:4000


###published link on render.com
https://web-app-project1.onrender.com/

###Get Math256
GET http://localhost:3000/math

###Get one student
GET http://localhost:3000/math/667bdda79f3b7180bd0962ea

###Post request, add an item
POST http://localhost:3000 HTTP/1.1
Content-Type: application/json

{
  "firstname": "sentinelbaba",
  "lastname": "prime",
  "birthdate": "01/02/1996",
  "country": "uganda",
  "email": "sentinelprime@gmail.com",
  "photo": "img/jpg",
  "major": "software development",
  "password": "huhuhu",
  "phone": "+25676788776"
}

###Update an item, put request
PUT http://localhost:3000/math/66a39d9eb91a5817e3237310 HTTP/1.1
Content-Type: application/json

{
  "firstname": "sentinel",
  "lastname": "prime",
  "birthdate": "01/02/1996",
  "country": "uganda",
  "email": "sentinelprime@test.com",
  "photo": "img/jpg",
  "major": "software development",
  "password": "hush-pswd",
  "phone": "+25676788776"
  }

###Delete request
DELETE http://localhost:3000/math/66a314103358b2dfb2762f59 HTTP/1.1
